repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.11
    hooks:
      - id: uv-lock
      - id: uv-export
      - id: pip-compile
        args: [requirements.in, -o, requirements.txt]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format