.githubname: Robot Reefscape CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --all-extras --dev
    
    - name: Check formatting
      run: |
        ruff format --check .
    
    - name: Lint with Ruff
      run: |
        ruff check .
    
    - name: Type check with mypy
      run: |
        pyright 
    
    - name: Test with pytest
      run: |
        uv run robotpy test